### ISSUE TITLE
WebView render issue

### ISSUE THREAD

**Issue by ZakariyaF** [ZakariyaF/WikiBrowser#3]
WebView does not render Wikipedia pages on devices running Android N and higher.

**Comment by ZakariyaF** [comment]
The file in question:
https://github.com/ZakariyaF/WikiBrowser/blob/master/app/src/main/java/com/zakariyaf/wikibrowser/activities/ArticleDetailActivity.kt

**Comment by vincent-paing** [comment]
Let me check

**Comment by ZakariyaF** [comment]
Thank you very much!
